import { Inter } from 'next/font/google';
import './globals.css';
import Theme from './theme';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <Theme>
        {' '}
        <body className={inter.className}>{children}</body>
      </Theme>
    </html>
  );
}
